### PR TITLE
Add meta names supported by most browsers

### LINKED ISSUE #3: [feature request] Allow for 'description', 'keywords' and 'author' properties without prefix
Hello, google search results uses 'description', 'keywords' and 'author' meta tags amongst others. It would be amazing if this module could allow to set those fields, fields without any prefix.

This is because 'dc.description' and 'dcterms.description' and the like are completely ignored by most (regular web) search engines [1-2].

I also tried using CustomOntology to achieve this but it seems that custom vocabularies are not used to drive the available fields in ResourceMeta (maybe nice as a separate feature request).

Thank you for making this plugin as the fields available do help with academic indexing already. I hope we can expand this to make it work for general search results. This would likely dramatically improve the find ability of museums using Omeka-s

1. [developers.google.com](https://developers.google.com/search/docs/fundamentals/seo-starter-guide?visit_id=638186176185769908-2364382001&rd=1#descriptionmeta)
2. [supported tags](https://developers.google.com/search/docs/crawling-indexing/special-tags)

### PR DESCRIPTION
**Pull request by Dantali0n**
Adds support for meta tags used by most browser for Search Engine Optimizations (SEO)

Closes: #3

### CODE REVIEW

**Comment by jimsafley** [comment]
On the links you provided in #3, I see `description` as a supported meta name, but I don't see `author`, `date`, or `keywords`.

**Comment by Dantali0n** [comment]
That is a fair point, here is an article by mozilla:
1. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name

I can't seem to find `date` on other resources though, I see `article:published_time` being used instead. Sometimes the date is also added to the path of the URL which is picked up by most search engines e.g `example.tld/2023/05/12/my-new-toy`.

Reference about `published_time`: https://stackoverflow.com/questions/29748013/what-is-the-correct-implementation-of-the-open-graph-article-type

`Keywords`, should be noted is being used less and less as it was used by spammers to abuse SEO.

There is also `og:image`, `og:title` and `og:description` these control how previews are rendered when URLs are pasted in social media like facebook, twitter, discord etc. Reference: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#other_types_of_metadata

But this is the root of the problem, we probably can't go and chase all these different meta tags  and every case they are used in. Instead it is likely better to provide sane defaults and allow users to set anything they think they need or like.

I'll update the patch to remove `date`, I can also remove `keywords` if you'd like and I'll add the Open Graph tags for the date and the previews.

**Comment by jimsafley** [comment]
Like I mentioned in #4, the [Sharing](https://github.com/omeka-s-modules/Sharing) module provides Open Graph tags. For this module I can see including `og:title` and `og:description`. Have you considered adding `og:type`? I'm not sure about adding `og:image` since representative images are assigned as media, not literal property values. I'm also reluctant to add something as specific as `og:article:published_time`, given that most resources are not articles.

In the end, it may be best to point users to the Sharing module if they need Open Graph. It follows the specification more closely than is possible with this module..

**Comment by Dantali0n** [comment]
Understandable, let's keep it to `author` and `description` then.

**Comment by jimsafley** [comment]
Thank you for the PR and good discussion.

**Pull request merged**
